// <auto-generated />
using System;
using Estoque_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estoque_App.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240825144813_NovoCampo")]
    partial class NovoCampo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Estoque_App.Data.Entities.Midia", b =>
                {
                    b.Property<Guid>("MidiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoMidia")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MidiaId");

                    b.ToTable("Midias");
                });

            modelBuilder.Entity("Estoque_App.Data.Entities.Produto", b =>
                {
                    b.Property<Guid>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MidiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProdutoId");

                    b.HasIndex("MidiaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Estoque_App.Data.Entities.Produto", b =>
                {
                    b.HasOne("Estoque_App.Data.Entities.Midia", "Midia")
                        .WithMany("Produtos")
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Midia");
                });

            modelBuilder.Entity("Estoque_App.Data.Entities.Midia", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
